### PR TITLE
Add Riot.im Community Link

### PR DESCRIPTION
**Pull request by thinkholic**

### CODE REVIEW

**Comment by pathumego** [comment]
> @THPubs @pathumego and I see we've missed out branching model information put in CONTRIBUTING.md. Any thought on that?

@thinkholic I'll add what we discussed. I was wondering there should be  articles around in the wbe about this that we can use, right?

**Comment by pathumego** [comment]
https://nvie.com/posts/a-successful-git-branching-model/

**Comment by thinkholic** [comment]
> https://nvie.com/posts/a-successful-git-branching-model/
> git-flow

We can adapt some of practices from this.

**Comment by pathumego** [comment]
Okay lets merge this for now and open a new PR for the branching model

**Pull request merged**
